plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.16'
    id 'io.spring.dependency-management' version '1.1.7'
    id "co.uzzu.dotenv.gradle" version "4.0.0"  //gradle에서 .env 사용
}

group = 'com.codeit'
version = '0.0.1-SNAPSHOT'
description = 'deokhugam-batch'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()

//    actions를 위해 getenv, 로컬을 위해 env.__.value
    maven {
        def githubRepository = System.getenv("GITHUB_REPOSITORY") ?: env.GITHUB_REPOSITORY.value
        def githubActor = System.getenv("GITHUB_ACTOR") ?: env.GITHUB_ACTOR.value
        def githubToken = System.getenv("GITHUB_TOKEN") ?: env.GITHUB_TOKEN.value

        url = uri("https://maven.pkg.github.com/${githubRepository}")

        credentials {
            username = githubActor
            password = githubToken
        }
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    runtimeOnly 'com.h2database:h2'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

//    공통 패키지 의존성 추가
    implementation 'com.codeit:deokhugam-common:1.0.0'
}

tasks.named('test') {
    useJUnitPlatform()
}
