spring:
  application:
    name: deokhugam-batch
    version: 0.0.1
  profiles:
    active: dev-batch

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        jdbc.time_zone: UTC

  ai:
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: "https://generativelanguage.googleapis.com"
      chat:
        options:
          model: "gemini-2.5-flash"

# log
logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type.descriptor.sql: trace
    org.springframework.web: trace
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

